version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: job-forge-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # UI management
    environment:
      RABBITMQ_DEFAULT_USER: jobforge
      RABBITMQ_DEFAULT_PASS: jobforge
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: